### ISSUE TITLE
tag normalization:  "tag" vs "' tag'"

### ISSUE THREAD

**Issue by metasj** [Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker#81]
Currently: having spaces b/t comma separated tags in the sheet (`legal, haloed`) leaves the leading space in all tags after the first (`legal, ' haloed'`).  They display in a normalized way on the website.

Desired effect:
* **Normalize github md tags**: convert tags to not having leading spaces; if tags can have spaces, put quotes around single words as well
* **Normalize spreadsheet tags**: put spaces into the string of tags in the spreadsheet

**Comment by agnescameron** [comment]
I think I fixed this a while ago -- either way, this no longer happens!
