### ISSUE TITLE
Add favicon 

### ISSUE THREAD

**Issue by metasj** [Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker#84]
32 and 192 px versions:

![favicon-32x32](https://user-images.githubusercontent.com/1615548/139130036-7ba019f5-b29d-45e0-aedd-d07d690cfc1f.png)

![android-chrome-192x192](https://user-images.githubusercontent.com/1615548/139130061-cabd6f91-05c0-4ac7-bd4e-abdd9354d7db.png)

**Comment by agnescameron** [comment]
done :)
