### ISSUE TITLE
I³ wordmark

### ISSUE THREAD

**Issue by metasj** [Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker#86]
Somewhere below the importance of choosing the logo, we should standardize I³ as a string / mark –  I propose using the unicode ³ character b/c it's easy to replicate in lots of environments.  

This has the downside that it's picked up differently by most search engines.

I updated the index page to ³, see what you think.

**Comment by agnescameron** [comment]
++ updated sitewide
