### ISSUE TITLE
URL overflows bounding box

### ISSUE THREAD

**Issue by metasj** [Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker#95]
https://i3-index.netlify.app/datasets/google_patents_public

**Comment by agnescameron** [comment]
this is fine for me -- what browser are you using?

<img width="855" alt="Screenshot 2021-12-02 at 17 08 22" src="https://user-images.githubusercontent.com/16444898/144469534-8fc763d9-c305-4f82-9d68-dc46cb887a60.png">

**Comment by metasj** [comment]
OS X/Chrome 94

<img width="693" alt="Screen Shot 2021-12-02 at 12 14 31" src="https://user-images.githubusercontent.com/1615548/144470639-0523239d-e15a-4505-a7f3-9816c965e84e.png">

**Comment by agnescameron** [comment]
fixed in commit e427dcebc266eaf7430d2781716cfba66cab736f (added word-wrap css property)
